CREATE SCHEMA `JWAT`
DEFAULT CHARACTER SET utf8
COLLATE utf8_bin ;

CREATE TABLE `JWAT`.`COUNTRY` (
  `ID` varchar(36) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`ID`),
  UNIQUE KEY `ID_UNIQUE` (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`PORT` (
  `PORT_ID` varchar(36) NOT NULL,
  `CODE` varchar(36) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `COUNTRY` varchar(36) NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`PORT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`ROUTE` (
  `ROUTE_ID` varchar(36) NOT NULL,
  `SOURCE_PORT_ID` varchar(36) NOT NULL,
  `DEST_PORT_ID` varchar(36) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`ROUTE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`SHIP` (
  `SHIP_ID` varchar(36) NOT NULL,
  `NAME` varchar(255) NOT NULL,
  `CAPACITY` int NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`SHIP_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`SHIPMENT` (
  `SHIPMENT_ID` varchar(36) NOT NULL,
  `CARGO_CONTENT` varchar(255) NOT NULL,
  `TEQ_QUANTITY` int NOT NULL,
  `TOTAL_COST` double DEFAULT NULL,
  `SHIP_REQUEST_DATE` datetime NOT NULL,
  `NEED_BY_DATE` datetime NOT NULL,
  `STATUS` varchar(50) NOT NULL,
  `INSURANCE_FLAG` varchar(255) DEFAULT NULL,
  `INSURANCE_AMOUNT` double DEFAULT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`SHIPMENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`USER` (
  `USER_ID` VARCHAR(36) NOT NULL,
  `LOGIN_NAME` VARCHAR(255) NOT NULL,
  `FIRST_NAME` VARCHAR(255) NOT NULL,
  `LAST_NAME` VARCHAR(255) NOT NULL,
  `PHONE` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(255) NOT NULL,
  `ADDRESS` VARCHAR(255),
  `CITY` VARCHAR(255),
  `STATE` VARCHAR(255),
  `POSTAL_CODE` VARCHAR(10),
  `COUNTRY` VARCHAR(36) NOT NULL,
  `ROLE` VARCHAR(36) NOT NULL,
  `PASSWORD` VARCHAR(255) NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`USER_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE `JWAT`.`USER_SHIPMENT` (
  `USER_SHIPMENT_ID` varchar(36) NOT NULL,
  `USER_ID` varchar(36) NOT NULL,
  `SHIPMENT_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`USER_SHIPMENT_ID`,`USER_ID`,`SHIPMENT_ID`),
  KEY `FK_USER_SHIPMENT_USER` (`USER_ID`),
  KEY `FK_USER_SHIPMENT_SHIPMENT` (`SHIPMENT_ID`),
  CONSTRAINT `FK_USER_SHIPMENT_SHIPMENT` FOREIGN KEY (`SHIPMENT_ID`) REFERENCES `shipment` (`SHIPMENT_ID`),
  CONSTRAINT `FK_USER_SHIPMENT_USER` FOREIGN KEY (`USER_ID`) REFERENCES `user` (`USER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`VOYAGE` (
  `VOYAGE_ID` VARCHAR(36) NOT NULL,
  `SHIP_ID` VARCHAR(36) NOT NULL,
  `ROUTE_ID` VARCHAR(36) NOT NULL,
  `START_DATE` DATETIME NOT NULL,
  `END_DATE` DATETIME NOT NULL,
  `VOYAGE_QUANTITY` INT(10) NOT NULL,
  `COST_PER_TEQ` DOUBLE NOT NULL,
  `IS_DELETED` tinyint DEFAULT '0',
  PRIMARY KEY (`VOYAGE_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `JWAT`.`VOYAGE_SHIPMENT` (
  `VOYAGE_SHIPMENT_ID` varchar(36) NOT NULL,
  `VOYAGE_ID` varchar(36) NOT NULL,
  `SHIPMENT_ID` varchar(36) NOT NULL,
  PRIMARY KEY (`VOYAGE_SHIPMENT_ID`,`VOYAGE_ID`,`SHIPMENT_ID`),
  KEY `FK_VOYAGE_SHIPMENT_VOYAGE` (`VOYAGE_ID`),
  KEY `FK_VOYAGE_SHIPMENT_SHIPMENT` (`SHIPMENT_ID`),
  CONSTRAINT `FK_VOYAGE_SHIPMENT_SHIPMENT` FOREIGN KEY (`SHIPMENT_ID`) REFERENCES `shipment` (`SHIPMENT_ID`),
  CONSTRAINT `FK_VOYAGE_SHIPMENT_VOYAGE` FOREIGN KEY (`VOYAGE_ID`) REFERENCES `voyage` (`VOYAGE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `JWAT`.`VOYAGE`
ADD CONSTRAINT `FK_VOYAGE_SHIP` FOREIGN KEY (`SHIP_ID`) REFERENCES `SHIP` (`SHIP_ID`);
ALTER TABLE `JWAT`.`VOYAGE` 
ADD CONSTRAINT `FK_VOYAGE_ROUTE` FOREIGN KEY (`ROUTE_ID`) REFERENCES `ROUTE` (`ROUTE_ID`);

ALTER TABLE `JWAT`.`ROUTE`
ADD CONSTRAINT `FK_ROUTE_SOURCE_PORT` FOREIGN KEY (`SOURCE_PORT_ID`) REFERENCES `PORT` (`PORT_ID`);
ALTER TABLE `JWAT`.`ROUTE`
ADD CONSTRAINT `FK_ROUTE_DEST_PORT` FOREIGN KEY (`DEST_PORT_ID`) REFERENCES `PORT` (`PORT_ID`);

ALTER TABLE `JWAT`.`PORT`
ADD CONSTRAINT `FK_PORT_COUNTRY` FOREIGN KEY (`COUNTRY`) REFERENCES `COUNTRY` (`ID`);

ALTER TABLE `JWAT`.`USER`
ADD CONSTRAINT `FK_USER_COUNTRY` FOREIGN KEY (`COUNTRY`) REFERENCES `COUNTRY` (`ID`);

